--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    networking.gke.io/load-balancer-type: Internal
  labels: 
    app: approject
  name: ilb-service
spec: 
  ports: 
    - 
      port: 80
      protocol: TCP
      targetPort: 8080
  selector: 
    app: approject
  type: LoadBalancer
