--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: psqltest
spec: 
  selector: 
    matchLabels: 
      app: approject
  template: 
    metadata: 
      labels: 
        app: approject
    spec: 
      containers: 
        - 
          env: 
            - 
              name: DB_USER
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: cloudsql-db-credentials
            - 
              name: DB_PASS
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: cloudsql-db-credentials
            - 
              name: DB_NAME
              valueFrom: 
                secretKeyRef: 
                  key: database
                  name: postgres
          name: approject
        - 
          command: 
            - /cloud_sql_proxy
            - "--dir=/cloudsql"
            - "-instances=customer-n-test-service:us-central1:testins=tcp:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          image: "gcr.io/cloudsql-docker/gce-proxy:latest"
          name: cloud-sql-proxy
          resources: 
            requests: 
              cpu: "1"
              memory: 2Gi
          securityContext: 
            runAsNonRoot: true
      serviceAccountName: test-psql-account
