--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prod-environment-deployment
spec: 
  selector: 
    matchLabels: 
      app: approject
  template: 
    metadata: 
      labels: 
        app: approject
    spec: 
      containers: 
        - 
          env: 
            - 
              name: DB_USER
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: cloudsql-db-credentials
            - 
              name: DB_PASS
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: cloudsql-db-credentials
            - 
              name: DB_NAME
              value: postgres
          image: "us-central1-docker.pkg.dev/customer-n-test-service/hello-repo/test-app:v1"
          name: approject
        - 
          command: 
            - /cloud_sql_proxy
            - "-instances=customer-n-prod-service-324106:us-central1:psql-prod-instance=tcp:5432"
          image: "gcr.io/cloudsql-docker/gce-proxy:latest"
          name: cloud-sql-proxy
          resources: 
            requests: 
              cpu: 200m
              memory: 32Mi
          securityContext: 
            runAsNonRoot: true
      serviceAccountName: testapp
