--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test
spec: 
  selector: 
    matchLabels: 
      app: approject
  template: 
    metadata: 
      labels: 
        app: approject
    spec: 
      containers: 
        - name: hello-app
          image: "us-central1-docker.pkg.dev/customer-n-test-service/hello-repo/hello-app:v1"  
          env: 
            - 
              name: DB_USER
              valueFrom:  
                secretKeyRef: 
                  key: username
                  name: postgress-credentials
            - 
              name: DB_PASS
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: postgress-credentials
            - 
              name: DB_NAME
              valueFrom: 
                secretKeyRef: 
                  key: databse
                  name: postgres-config
          name: approject
        - 
          command: 
            - /cloud_sql_proxy
            - "--dir=/cloudsql"
            - "-instances=customer-n-test-service:us-central1:testinstance=tcp:5432" 
            - "-credential_file=/secrets/cloudsql/credentials.json"
          image: "gcr.io/cloudsql-docker/gce-proxy:latest"
          name: cloud-sql-proxy
          resources: 
            requests:   
              cpu: "200m"
              memory: "32Mi" 
          securityContext: 
            runAsNonRoot: true
      serviceAccountName: testapp 
