# [START cloud_sql_proxy_k8s_sa]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psqldeployment
spec:
  selector:
    matchLabels:
      app: PSQLConProject
  template:
    metadata:
      labels:
        app: PSQLConProject
    spec:
      serviceAccountName: psqlproject
      # [END cloud_sql_proxy_k8s_sa]
      # [START cloud_sql_proxy_k8s_secrets]
      containers:
      - name: PSQLConProject
        # ... other container configuration
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: vrithika
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: e5sbcbc!Q|hoky1k
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
      # [END cloud_sql_proxy_k8s_secrets]
      # [START cloud_sql_proxy_k8s_container]
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
        "-instances=34.66.225.19=tcp:5432",
        "-credential_file=customer-n-test-service-f0c309072063.json"]  

        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: cloudsql
            mountPath: /cloudsql
      # volumes
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: 
